Se reestructura proceso de despliegue

diff --git a/.github/workflows/build-and-deploy-orders.yml b/.github/workflows/build-and-deploy-orders.yml
--- a/.github/workflows/build-and-deploy-orders.yml
+++ b/.github/workflows/build-and-deploy-orders.yml
@@ -1,10 +1,10 @@
-name: Deploy to Cloud Run
+name: Build and Deploy Orders Management
 
 on:
   workflow_dispatch: # Permite la ejecución manual
 
 jobs:
-  deploy:
+  build_deploy:
     runs-on: ubuntu-latest
 
     steps:
@@ -21,6 +21,36 @@ jobs:
         with:
           project_id: ${{ secrets.GCP_PROJECT_ID }}
 
+      - name: Get Cloud SQL Instance Private IP
+        id: get_ip
+        run: |
+          echo "Obteniendo las IPs de la instancia..."
+          IP_ADDRESSES=$(gcloud sql instances describe postgres --format="value(ipAddresses)")
+          if [ -z "$IP_ADDRESSES" ]; then
+            echo "Error: No se encontraron IPs para la instancia."
+            exit 1
+          fi
+          echo "Extrayendo la IP privada..."
+          PRIVATE_IP=$(echo "$IP_ADDRESSES" | grep -oP "'ipAddress': '\K[0-9.]+(?=', 'type': 'PRIVATE')")
+          if [ -z "$PRIVATE_IP" ]; then
+            echo "Error: No se pudo obtener la IP privada."
+            echo "IPs encontradas: $IP_ADDRESSES"
+            exit 1
+          fi
+          echo "IP privada: $PRIVATE_IP"
+          echo "::set-output name=db_ip::$PRIVATE_IP"
+
+      - name: Update ./orders-management/src/.env.development
+        run: |
+          echo "Current directory: $(pwd)"
+          ls -la
+          sed -i "s/DB_HOST=localhost/DB_HOST=${{ steps.get_ip.outputs.db_ip }}/g" ./orders-management/src/.env.development
+
+      - name: Build and Push Docker Image Orders
+        run: |
+          docker build -t us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/orders-management-image:latest ./orders-management
+          docker push us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/orders-management-image:latest
+
       - name: Create VPC Access Connector
         id: create_vpc_connector
         run: |
@@ -34,7 +64,7 @@ jobs:
           else
             echo "El VPC Connector ya existe. Saltando creación."
           fi
-
+  
       - name: Deploy to Cloud Run Orders
         run: |
           gcloud run deploy orders-management-service \
@@ -48,18 +78,5 @@ jobs:
             --port=5001 \
             --vpc-connector=orders-vpc-connector \
             --vpc-egress=private-ranges-only
-
-
-      - name: Deploy to Cloud Run Products
-        run: |
-          gcloud run deploy products-management-service \
-            --image=us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/products-management-image:latest \
-            --region=us-central1 \
-            --platform=managed \
-            --allow-unauthenticated \
-            --memory=512Mi \
-            --cpu=1 \
-            --concurrency=80 \
-            --port=5002 \
-            --vpc-connector=orders-vpc-connector \
-            --vpc-egress=private-ranges-only
+            --min-instances=1
+            --max-instances=3
